package generator

import (
	"fmt"
	"text/template"
	"time"
)

var templateFuncMap = template.FuncMap{
	"generatedDisclaimer": generatedDisclaimer,
}

// generatedDisclaimer returns a disclaimer string with the current date and time
func generatedDisclaimer() string {
	return fmt.Sprintf("// Code generated by mcpgen. DO NOT EDIT. Generated at: %s\n", time.Now().Format(time.RFC3339))
}
